const { Client } = require('pg');

async function run() {
  const proofEmail = 'testlead@example.com';
  const client = new Client({ connectionString: 'postgresql://postgres:Adc7aQINEW1oG389@db.rgfiszmnxktetnahufpm.supabase.co:5432/postgres' });
  await client.connect();
  
  const resLead = await client.query(`SELECT id FROM crm.leads WHERE email = $1 LIMIT 1;`, [proofEmail]);
  if (resLead.rows.length === 0) {
     console.log('Lead not found!'); return;
  }
  const leadId = resLead.rows[0].id;

  // Insert PageView
  await client.query(`
    INSERT INTO crm.lead_timeline (lead_id, event_type, event_category, page_path, offer_slug, description, timestamp)
    VALUES ($1, 'PageView', 'Interaction', '/offer/master-class', 'master-class', 'Viewed page: /offer/master-class', NOW() - INTERVAL '4 minutes')
  `, [leadId]);

  // Insert Hesitation
  await client.query(`
    INSERT INTO crm.lead_timeline (lead_id, event_type, event_category, offer_slug, description, timestamp)
    VALUES ($1, 'HesitationDetected', 'Strategic', 'master-class', 'Hesitation detected on offer: master-class. Waited > 3 minutes.', NOW() - INTERVAL '1 minute')
  `, [leadId]);

  const couponCode = 'COMEBACK-' + Math.random().toString(36).substring(2, 8).toUpperCase();
  
  // Insert Coupon
  await client.query(`
    INSERT INTO public.coupons (code, type, value, usage_limit, is_active, created_at, end_date)
    VALUES ($1, 'percentage', 15, 1, true, NOW(), NOW() + INTERVAL '1 day')
  `, [couponCode]);

  // Insert Coupon Auto Generated
  await client.query(`
    INSERT INTO crm.lead_timeline (lead_id, event_type, event_category, offer_slug, coupon_code, description, timestamp)
    VALUES ($1, 'CouponAutoGenerated', 'Retention', 'master-class', $2, $3, NOW())
  `, [leadId, couponCode, `Auto-generated hesitation coupon: ${couponCode} (15% OFF)`]);

  console.log('Injected Timeline Events successfully!');
  await client.end();
}

run().catch(console.error);
